name: Nightly build Ubuntu

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
   
    steps:
    - uses: actions/checkout@v1

    - name: install_dependencies
      run: |
        sudo apt-get -y update
        sudo apt-get -ym install libpng-dev
        sudo apt-get -ym install libsdl2-dev
        sudo apt-get -ym install libbz2-dev
        sudo apt-get -ym install autoconf
        svn checkout svn://servers.simutrans.org/simutrans simutrans
    - name: setup
      run: |
        cd simutrans/trunk
        autoconf
        ./configure
        cat config.default >>/dev/stderr
    - name: make makeobj
      run: |
          cd simutrans/trunk/makeobj
          echo $PWD
          make
          mv makeobj ../../..
          cd ../../..
          zip -r makeobj.zip makeobj

    - name: make pak192
      run: |
        bash COMPILE_THEME.sh
    - name: Update binaries of Nightly Release
      uses: svenstaro/upload-release-action@v1-release
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: ./themes.zip
        asset_name: themes.zip
        tag: Nightly
        overwrite: true
